# Generated by Django 4.2 on 2023-04-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iweatherapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='city',
        ),
    ]
